#service:
#- docker

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

#addons:
#  apt:
#    update: true
#    packages:
#    - sudo
#    - lsof
#    - bash
#    - unzip
#    - curl
#    - jq
#    - libxml2-utils
#    - docker-ce
#    - python-pip

install: true
#before_script:
#- sudo pip install docker-compose httpie >/dev/null 2>&1
#- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

script:
- bash mvnw >/dev/null
- bash gradlew >/dev/null

before_deploy: ./gradlew documentation

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages

before_cache:
- sudo rm -rf $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- sudo rm -rf $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
- sudo rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.docker
